/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVisualRouteImport } from './routes/app.visual'
import { Route as AppSessionRouteImport } from './routes/app.session'
import { Route as AppReflectionRouteImport } from './routes/app.reflection'
import { Route as AppQuickStartRouteImport } from './routes/app.quick-start'
import { Route as AppLiveRouteImport } from './routes/app.live'
import { Route as AppExperienceRouteImport } from './routes/app.experience'
import { Route as AppEvolutionRouteImport } from './routes/app.evolution'
import { Route as AppActivitiesRouteImport } from './routes/app.activities'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisualRoute = AppVisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppReflectionRoute = AppReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => AppRoute,
} as any)
const AppQuickStartRoute = AppQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppExperienceRoute = AppExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/experience': typeof AppExperienceRoute
  '/app/live': typeof AppLiveRoute
  '/app/quick-start': typeof AppQuickStartRoute
  '/app/reflection': typeof AppReflectionRoute
  '/app/session': typeof AppSessionRoute
  '/app/visual': typeof AppVisualRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/experience': typeof AppExperienceRoute
  '/app/live': typeof AppLiveRoute
  '/app/quick-start': typeof AppQuickStartRoute
  '/app/reflection': typeof AppReflectionRoute
  '/app/session': typeof AppSessionRoute
  '/app/visual': typeof AppVisualRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/activities': typeof AppActivitiesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/experience': typeof AppExperienceRoute
  '/app/live': typeof AppLiveRoute
  '/app/quick-start': typeof AppQuickStartRoute
  '/app/reflection': typeof AppReflectionRoute
  '/app/session': typeof AppSessionRoute
  '/app/visual': typeof AppVisualRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/activities'
    | '/app/evolution'
    | '/app/experience'
    | '/app/live'
    | '/app/quick-start'
    | '/app/reflection'
    | '/app/session'
    | '/app/visual'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/activities'
    | '/app/evolution'
    | '/app/experience'
    | '/app/live'
    | '/app/quick-start'
    | '/app/reflection'
    | '/app/session'
    | '/app/visual'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/activities'
    | '/app/evolution'
    | '/app/experience'
    | '/app/live'
    | '/app/quick-start'
    | '/app/reflection'
    | '/app/session'
    | '/app/visual'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visual': {
      id: '/app/visual'
      path: '/visual'
      fullPath: '/app/visual'
      preLoaderRoute: typeof AppVisualRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/session': {
      id: '/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reflection': {
      id: '/app/reflection'
      path: '/reflection'
      fullPath: '/app/reflection'
      preLoaderRoute: typeof AppReflectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quick-start': {
      id: '/app/quick-start'
      path: '/quick-start'
      fullPath: '/app/quick-start'
      preLoaderRoute: typeof AppQuickStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experience': {
      id: '/app/experience'
      path: '/experience'
      fullPath: '/app/experience'
      preLoaderRoute: typeof AppExperienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evolution': {
      id: '/app/evolution'
      path: '/evolution'
      fullPath: '/app/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activities': {
      id: '/app/activities'
      path: '/activities'
      fullPath: '/app/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppExperienceRoute: typeof AppExperienceRoute
  AppLiveRoute: typeof AppLiveRoute
  AppQuickStartRoute: typeof AppQuickStartRoute
  AppReflectionRoute: typeof AppReflectionRoute
  AppSessionRoute: typeof AppSessionRoute
  AppVisualRoute: typeof AppVisualRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppEvolutionRoute: AppEvolutionRoute,
  AppExperienceRoute: AppExperienceRoute,
  AppLiveRoute: AppLiveRoute,
  AppQuickStartRoute: AppQuickStartRoute,
  AppReflectionRoute: AppReflectionRoute,
  AppSessionRoute: AppSessionRoute,
  AppVisualRoute: AppVisualRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
